# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install dependency modules
        run: npm install

      - name: Run a test
        run: npm run test

      - name: Run a test
        run: npm run docs

      - name: Run a build
        run: npm run build:webpack

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "maetaro/maetaro.github.io"
          ref: "master"
          path: "maetaro.github.io"

      - name: File Copy
        run: |
          rm -rf maetaro.github.io/reversi
          cp -rf dist maetaro.github.io/reversi
      - name: Deploy Configuration
        run: |
          mkdir ~/.ssh
          ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.MY_ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
      - name: Push
        env:
          GITHUB_USER: "builduser"
          GITHUB_EMAIL: "test-builduser@sample.com"
          GITHUB_REPOSITORY: "maetaro/maetaro.github.io"
        run: |
          cd maetaro.github.io
          git config --local user.name "${GITHUB_USER}"
          git config --local user.email "${GITHUB_EMAIL}"
          git remote set-url origin git@github.com:maetaro/maetaro.github.io.git
          git config remote.origin.url "git@github.com:maetaro/maetaro.github.io.git"
          git add reversi
          git commit -m "auto rebuilding site"
          git push origin master
